apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
    visualize: "true"
    app: "nextdemo"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: frontend
    app: nextdemo
#createExternalLoadBalancer: true
