apiVersion: v1beta3
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: frontend
  createExternalLoadBalancer: true
