apiVersion: v1
kind: Pod 
metadata:
  name: memcached
  labels: 
    name: memcached
    visualize: "true"
    app: nextdemo
spec:
  containers:
    - image: memcached:1.4
      name: memcached
      ports:
        - containerPort: 11211
          name: memcached
