apiVersion: v1beta3
kind: Pod 
metadata:
  name: memcached
  labels: 
    name: memcached
spec:
  containers:
    - image: memcached:1.4
      name: memcached
      ports:
        - containerPort: 11211
          name: memcached
